package runner

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"

	"github.com/btraven00/obflow/internal/config"
)

const pixiManifestName = "pixi.toml"

// EnsurePixiManifest writes (or rewrites if changed) <workspaceDir>/.obflow/pixi.toml
// for use with the conda backend. Returns the manifest path and whether it
// was (re)written this call.
func EnsurePixiManifest(workspaceDir string, omni config.Omnibenchmark) (string, bool, error) {
	dir := filepath.Join(workspaceDir, config.DirName)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return "", false, err
	}
	p := filepath.Join(dir, pixiManifestName)
	want := renderPixi(omni)
	if existing, err := os.ReadFile(p); err == nil && string(existing) == want {
		return p, false, nil
	}
	if err := os.WriteFile(p, []byte(want), 0644); err != nil {
		return "", false, err
	}
	return p, true, nil
}

func renderPixi(o config.Omnibenchmark) string {
	return fmt.Sprintf(`# generated by obflow; do not edit by hand
[workspace]
name = "obflow"
channels = ["conda-forge"]
platforms = ["%s"]

[dependencies]
python = "3.12.*"
conda = "*"

[pypi-dependencies]
omnibenchmark = %s
`, pixiPlatform(), pixiOmniSpec(o))
}

func pixiPlatform() string {
	switch runtime.GOOS + "/" + runtime.GOARCH {
	case "linux/amd64":
		return "linux-64"
	case "linux/arm64":
		return "linux-aarch64"
	case "darwin/arm64":
		return "osx-arm64"
	case "darwin/amd64":
		return "osx-64"
	case "windows/amd64":
		return "win-64"
	default:
		return "linux-64"
	}
}

func pixiOmniSpec(o config.Omnibenchmark) string {
	if o.PR != 0 {
		return fmt.Sprintf(`{ git = "%s", rev = "refs/pull/%d/head" }`, config.UpstreamRepo, o.PR)
	}
	if o.Branch != "" {
		return fmt.Sprintf(`{ git = "%s", branch = "%s" }`, config.UpstreamRepo, o.Branch)
	}
	if o.Version != "" {
		return fmt.Sprintf(`"==%s"`, o.Version)
	}
	return `"*"`
}
